export const FETCH_BLOGS_REQUEST = "FETCH_BLOGS_REQUEST";
export const FETCH_BLOGS_SUCCESS = "FETCH_BLOGS_SUCCESS";
export const FETCH_BLOGS_ERROR = "FETCH_BLOGS_ERROR";

export const GET_BLOG_REQUEST = "GET_BLOG_REQUEST";
export const GET_BLOG_SUCCESS = "GET_BLOG_SUCCESS";
export const GET_BLOG_ERROR = "GET_BLOG_ERROR";

export const CREATE_BLOG_REQUEST = "CREATE_BLOG_REQUEST";
export const CREATE_BLOG_SUCCESS = "CREATE_BLOG_SUCCESS";
export const CREATE_BLOG_ERROR = "CREATE_BLOG_ERROR";

export const UPVOTE_BLOG_REQUEST = "UPVOTE_BLOG_REQUEST";
export const UPVOTE_BLOG_SUCCESS = "UPVOTE_BLOG_SUCCESS";
export const UPVOTE_BLOG_ERROR = "UPVOTE_BLOG_ERROR";

export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_ERROR = "ADD_COMMENT_ERROR";
